build:gfdl-ws:
  stage: build
  tags:
    - gfdl-ws
  script:
    - autoreconf --install
    - ./configure --prefix /home/fms/opt/gfdl-grtcode CFLAGS="-g -O2 -Wall -Wextra -pedantic -std=c99 -fopenmp" CPPFLAGS="-I/home/Raymond.Menzel/local/include" LDFLAGS="-fopenmp -L/home/Raymond.Menzel/local/lib"
    - make
  artifacts:
    untracked: true
    expire_in: 1 days


test:gfdl-ws:
  stage: test
  tags:
    - gfdl-ws
  variables:
    LD_LIBRARY_PATH: /home/Raymond.Menzel/local/lib
  script:
    - make check
  dependencies:
    - build:gfdl-ws


deploy:gfdl-ws:
  stage: deploy
  environment: gfdl-ws
  only:
    - master
  tags:
    - gfdl-ws_deploy
  script:
    - make install
  dependencies:
    - build:gfdl-ws


build:lscsky50-d:
  stage: build
  tags:
    - skylake
  script:
    - source /opt/lmod/lmod/init/bash
    - module load intel/2019_up2
    - autoreconf --install
    - ./configure --prefix /opt/gfdl-grtcode CC="icc" CFLAGS="-g -O2 -qopenmp" CPPFLAGS="-I/opt/hdf5/1.10.1/INTEL/include -I/opt/netcdf/4.6.1/INTEL/include" LDFLAGS="-qopenmp -L/opt/hdf5/1.10.1/INTEL/lib -L/opt/netcdf/4.6.1/INTEL/lib64" CXX="icc"
    - make
  artifacts:
    untracked: true
    expire_in: 1 days


test:lscsky50-d:
  stage: test
  tags:
    - skylake
  script:
    - source /opt/lmod/lmod/init/bash
    - module load intel/2019_up2 netcdf/4.6.1
    - make check
  dependencies:
    - build:lscsky50-d


deploy:lscsky50-d:
  stage: deploy
  environment: skylake
  only:
    - master
  tags:
    - skylake
  script:
    - source /opt/lmod/lmod/init/bash
    - module load intel/2019_up2
    - make install
  dependencies:
    - build:lscsky50-d
